server:
  port: 8080

spring:
  application:
    name: reviews-api

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  docker:
    compose:
      lifecycle-management: start_only
      readiness:
        wait: never
      start:
        log-level: info


springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  expirationMs: 3600000 # 1 hour
