server:
  port: 8080

spring:
  application:
    name: reviews-api
  datasource:
    url: jdbc:postgresql://localhost:5432/reviewsdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: your_super_secret_jwt_key
  expirationMs: 3600000 # 1 hour
