spring:
  datasource:
    url: jdbc:postgresql://206.81.18.5:5436/reviewsdb
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${PROD_REDIS_HOST}
      port: ${PROD_REDIS_PORT}

  rabbitmq:
    host: localhost | ${PROD_RABBITMQ_HOST}
    port: 5672
    username: ${PROD_RABBITMQ_USERNAME}
    password: ${PROD_RABBITMQ_PASSWORD}



  docker:
    compose:
      profiles:
        active: prod

jwt:
  secret: ${PROD_JWT_SECRET}
