spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:25060/reviewsdb?sslmode=require
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: org.postgresql.Driver



  data:
    redis:
      host: ${PROD_REDIS_HOST}
      port: ${PROD_REDIS_PORT}
    jdbc:
      dialect: postgresql


  rabbitmq:
    host: localhost | ${PROD_RABBITMQ_HOST}
    port: 5672
    username: ${PROD_RABBITMQ_USERNAME}
    password: ${PROD_RABBITMQ_PASSWORD}



  docker:
    compose:
      profiles:
        active: prod
      enabled: true
  jpa:
    generate-ddl: false

jwt:
  secret: ${PROD_JWT_SECRET}
