spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/reviewsdb
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: ${PROD_RABBITMQ_HOST}
    port: 5672
    username: ${PROD_RABBITMQ_USERNAME}
    password: ${PROD_RABBITMQ_PASSWORD}


  docker:
    compose:
      profiles:
        active: dev


jwt:
  secret: ${JWT_SECRET}

rsa:
  private-key: ./private.pem
  public-key: ./public.pem