spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:25060/reviewsdb?sslmode=require
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: org.postgresql.Driver

  data:
    jdbc:
      dialect: postgresql
    redis:
      host: ${PROD_REDIS_HOST}
      port: ${PROD_REDIS_PORT}

  jpa:
    generate-ddl: false

  rabbitmq:
    host: localhost | ${PROD_RABBITMQ_HOST}
    port: 5672
    username: ${PROD_RABBITMQ_USERNAME}
    password: ${PROD_RABBITMQ_PASSWORD}
  docker:
    compose:
      enabled: true
      profiles:
        active: prod


rsa:
  private-key: ${RSA_PRIVATE_KEY}
  public-key: ${RSA_PUBLIC_KEY}

jwt:
  secret: ${PROD_JWT_SECRET}
