spring:
  datasource:
    url: jdbc:postgresql://reviews-db-do-user-18401247-0.j.db.ondigitalocean.com:25060/reviewsdb?sslmode=require
    username: root
    password: AVNS_-Nf7e1gDpyCSkS2M2BN
    name: org.postgresql.Driver



  data:
    redis:
      host: ${PROD_REDIS_HOST}
      port: ${PROD_REDIS_PORT}
    jdbc:
      dialect: postgresql


  rabbitmq:
    host: localhost | ${PROD_RABBITMQ_HOST}
    port: 5672
    username: ${PROD_RABBITMQ_USERNAME}
    password: ${PROD_RABBITMQ_PASSWORD}



  docker:
    compose:
      profiles:
        active: prod
      enabled: true
  jpa:
    generate-ddl: false

jwt:
  secret: ${PROD_JWT_SECRET}
