spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/reviewsdb
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672 # Note: Admin console is 15672, connection port is usually 5672
    username: guest
    password: guest


jwt:
  secret: ${JWT_SECRET}
