server:
  port: 8080

spring:
  profiles:
    active: prod
  application:
    name: reviews-api


  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    open-in-view: false


  docker:
    compose:
      lifecycle-management: start_only
      readiness:
        wait: never
      start:
        log-level: info
  devtools:
    livereload:
      enabled: off


springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  expirationMs: 3600000 # 1 hour




logging:
  level:
    root:  info

